version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # your backend Dockerfile
    container_name: rag-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # your frontend Dockerfile
    container_name: rag-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
